name: Pull Request

on:
  pull_request:
    branches: [ 'main', 'release/**' ]

jobs:
  build-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/build-deploy.yml
    with:
      deploy: true
      suffix: "pr${{ github.event.pull_request.number }}"

  comment-pr:
    name: Comment on PR with Build Info
    runs-on: ubuntu-latest
    needs: build-deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Post comment with build info
      run: |
        cat > pr-comment.md <<EOF
        # Build Info

        ## Maven Coordinates

        ### Linux x86 64 bits

        \`\`\`
        org.metricshub:metricshub-jre:${JRE_VERSION}:linux-x86_64
        \`\`\`

        \`\`\`xml
          <dependency>
            <groupId>org.metricshub</groupId>
            <artifactId>metricshub-jre</artifactId>
            <version>${JRE_VERSION}</version>
            <classifier>linux-x86_64</classifier>
            <type>zip</type>
          </dependency>
        \`\`\`

        ### Linux ARM 64 bits

        \`\`\`
        org.metricshub:metricshub-jre:${JRE_VERSION}:linux-aarch64
        \`\`\`

        \`\`\`xml
          <dependency>
            <groupId>org.metricshub</groupId>
            <artifactId>metricshub-jre</artifactId>
            <version>${JRE_VERSION}</version>
            <classifier>linux-aarch64</classifier>
            <type>zip</type>
          </dependency>
        \`\`\`

        ### Windows x86 64 bits

        \`\`\`
        org.metricshub:metricshub-jre:${JRE_VERSION}:windows-amd64
        \`\`\`

        \`\`\`xml
          <dependency>
            <groupId>org.metricshub</groupId>
            <artifactId>metricshub-jre</artifactId>
            <version>${JRE_VERSION}</version>
            <classifier>windows-amd64</classifier>
            <type>zip</type>
          </dependency>
        \`\`\`

        ## Docker Image
        \`\`\`
        docker pull ${{ needs.build-deploy.outputs.dockerImageTag }}
        \`\`\`
        EOF
        gh pr comment ${{ github.event.pull_request.number }} --create-if-none --edit-last --body-file pr-comment.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JRE_VERSION: ${{ needs.build-deploy.outputs.jreMavenVersion }}
